Feature: Validation users

  @validation_users_register_group_1
  Scenario Outline: Validation users in register group 1
    * that login with the 'https://possum-kingdom-open-water-swim-4lzlpd.public-staging.colliegives.com/experience/cm1gu0wdu039n0alb8jel9br0'
    Given that the user open page
      | userRegistration   | passwordRegistration   |
      | <userRegistration> | <passwordRegistration> |

    Examples:
      | userRegistration                                 | passwordRegistration |
      | kimberlydawn3+emerson@gmail.com                  | Gobi0501             |
      | kimberlydawn3+pgh1@gmail.com                     | Gobi0501             |
      | kimberlydawn3+clover@gmail.com                   | Gobi0501             |
      | kimberlydawn3+July23@gmail.com                   | Gobi0501             |
      | kimberlydawn3+July23+emerson@gmail.com           | Gobi0501             |
      | kimberlydawn3+july23+gary@gmail.com              | Gobi0501             |
      | kimberlydawn3+3@gmail.com                        | Gobi0501             |
      | kimberlydawn3+e1@gmail.com                       | Gobi0501             |
      | kimberlydawn3+judy@gmail.com                     | Gobi0501             |
      | kimberlydawn3+gobi@gmail.com                     | Gobi0501             |
      | kimberlydawn3+aug23@gmail.com                    | Gobi0501             |
      | kimberlydawn3+aug23+clover@gmail.com             | Gobi0501             |
      | kimberlydawn3+aug23+emerson@gmail.com            | Gobi0501             |
      | kimberlydawn3+aug23+bootsie@gmail.com            | Gobi0501             |
      | kimberlydawn3+aug23+alyeska@gmail.com            | Gobi0501             |
      | kimberlydawn3+aug23+dimetrodon@gmail.com         | Gobi0501             |
      | Kimberlydawn3+dinorescue@gmail.com               | Gobi0501             |
      | Kimberlydawn3+BCR+Beau@gmail.com                 | Gobi0501             |
      | kimberlydawn3+SSC+babyshark@gmail.com            | Gobi0501             |
      | kimberlydawn3+Sept23+emerson@gmail.com           | Gobi0501             |
      | kimberlydawn3+Sept23+clover@gmail.com            | Gobi0501             |
      | kimberlydawn3+Sept23+kilian@gmail.com            | Gobi0501             |
      | kimberlydawn3+Sept23+gobi@gmail.com              | Gobi0501             |
      | kimberlydawn3+Sept23+garym@gmail.com             | Gobi0501             |
      | kimberlydawn3+Sept23+alyeska@gmail.com           | Gobi0501             |
      | kimberlydawn3+Sept23+kronosaurus@gmail.com       | Gobi0501             |
      | kimberlydawn3+Sept23+spinosaurus@gmail.com       | Gobi0501             |
      | kimberlydawn3+Sept23+bingo@gmail.com             | Gobi0501             |
      | kimberlydawn3+Sept23+bootsie@gmail.com           | Gobi0501             |
      | kimberlydawn3+sept23+pmtest@gmail.com            | Gobi0501             |
      | kimberlydawn3+Sept23+mel@gmail.com               | Gobi0501             |
      | kimberlydawn3+Sept23+Ernie@gmail.com             | Gobi0501             |
      | kimberlydawn3+Sept23+barebumbear@gmaill.com      | Gobi0501             |
      | kimberlydawn3+Sept23+Judy@gmail.com              | Gobi0501             |
      | kimberlydawn3+Sept23+AustinBear@gmail.com        | Gobi0501             |
      | kimberlydawn3+Sept23+Mosasaurus@gmail.com        | Gobi0501             |
      | kimberlydawn3+KilianBC@gmail.com                 | Gobi0501             |
      | kimberlydawn3+Sept23+GreenDinosaur@gmail.com     | Gobi0501             |
      | kimberlydawn3+Sept23+BearBumBear@gmail.com       | Gobi0501             |
      | kimberlydawn3+bcr+kilian@gmail.com               | Gobi0501             |
      | kimberlydawn3+GCI+MGhisallo@gmail.com            | Gobi0501             |
      | kimberlydawn3+BWS+Batman@gmail.com               | Gobi0501             |
      | kimberlydawn3+CTFB+Carrot@gmail.com              | Gobi0501             |
      | kimberlydawn3+CTFB+Pumpkin@gmail.com             | Gobi0501             |
      | kimberlydawn3+Oct23+Pachycephalosaurus@gmail.com | Gobi0501             |
      | kimberlydawn3+Oct23+kilian@gmail.com             | Gobi0501             |
      | kimberlydawn3+Oct23+Mosasaurus@gmail.com         | Gobi0501             |
      | kimberlydawn3+Oct23+Gallimimus@gmail.com         | Gobi0501             |
      | kimberlydawn3+Oct23+Pteradactyl@gmail.com        | Gobi0501             |
      | kimberlydawn3+randallandrade@gmail.com           | Gobi0501             |
      | kimberlydawn3+geoffreywillis@gmail.com           | Gobi0501             |
      | kimberlydawn3+emilepeters@gmail.com              | Gobi0501             |
      | kimberlydawn3+ninariley@gmail.com                | Gobi0501             |
      | kimberlydawn3+laceycantu@gmail.com               | Gobi0501             |
      | kimberlydawn3+meganmiles@gmail.com               | Gobi0501             |
      | kimberlydawn3+krystalweber@gmail.com             | Gobi0501             |
      | kimberlydawn3+patrickray@gmail.com               | Gobi0501             |
      | kimberlydawn3+willcrawford@gmail.com             | Gobi0501             |
      | kimberlydawn3+trishalloyd@gmail.com              | Gobi0501             |
      | kimberlydawn3+kaybarajas@gmail.com               | Gobi0501             |
      | kimberlydawn3+ollieolsen@gmail.com               | Gobi0501             |
      | kimberlydawn3+oliviaolsen@gmail.com              | Gobi0501             |
      | kimberlydawn3+cruzruiz@gmail.com                 | Gobi0501             |
      | kimberlydawn3+jillmedina@gmail.com               | Gobi0501             |
      | kimberlydawn3+gabriellehardy@gmail.com           | Gobi0501             |
      | kimberlydawn3+leonklein@gmail.com                | Gobi0501             |
      | kimberlydawn3+rossalvarez@gmail.com              | Gobi0501             |
      | kimberlydawn3+jorgemorton@gmail.com              | Gobi0501             |
      | kimberlydawn3+jaydixon@gmail.com                 | Gobi0501             |
      | kimberlydawn3+felixwagner@gmail.com              | Gobi0501             |
      | kimberlydawn3+brantwoods@gmail.com               | Gobi0501             |
      | kimberlydawn3+alexcarrillo@gmail.com             | Gobi0501             |
      | kimberlydawn3+tarahayden@gmail.com               | Gobi0501             |
      | kimberlydawn3+clarawiley@gmail.com               | Gobi0501             |
      | kimberlydawn3+margerycortez@gmail.com            | Gobi0501             |
      | kimberlydawn3+gretchenhaley@gmail.com            | Gobi0501             |
      | kimberlydawn3+elizareynolds@gmail.com            | Gobi0501             |
      | kimberlydawn3+kimberleymeadows@gmail.com         | Gobi0501             |
      | kimberlydawn3+bcr+luna@gmail.com                 | Gobi0501             |
      | kimberlydawn3+jacobsmith@gmail.com               | Gobi0501             |
      | kimberlydawn3+kylecook@gmail.com                 | Gobi0501             |
      | kimberlydawn3+katiemay@gmail.com                 | Gobi0501             |
      | kimberlydawn3+jayblanton@gmail.com               | Gobi0501             |
      | kimberlydawn3+nicoleadams@gmail.com              | Gobi0501             |
      | kimberlydawn3+bcr+ripp@gmail.com                 | Gobi0501             |
      | kimberlydawn3+jenniferthomas@gmail.com           | Gobi0501             |
      | kimberlydawn3+aleccarrillo@gmail.com             | Gobi0501             |
      | kimberlydawn3+katrinacollins@gmail.com           | Gobi0501             |
      | kimberlydawn3+annemariebattikha@gmail.com        | Gobi0501             |
      | kimberlydawn3+jeffhines@gmail.com                | Gobi0501             |
      | kimberlydawn3+jenniferclarke@gmail.com           | Gobi0501             |
      | kimberlydawn3+jeremywright@gmail.com             | Gobi0501             |
      | kimberlydawn3+coramena@gmail.com                 | Gobi0501             |
      | kimberlydawn3+jeffmena@gmail.com                 | Gobi0501             |
      | kimberlydawn3+amyzola@gmail.com                  | Gobi0501             |
      | kimberlydawn3+barbarayates@gmail.com             | Gobi0501             |
      | kimberlydawn3+coryxavier@gmail.com               | Gobi0501             |
      | kimberlydawn3+danielwitten@gmail.com             | Gobi0501             |
      | kimberlydawn3+finleyupton@gmail.com              | Gobi0501             |
      | kimberlydawn3+gregtremont@gmail.com              | Gobi0501             |
      | kimberlydawn3+henryspeck@gmail.com               | Gobi0501             |
      | kimberlydawn3+elwaydaniels@gmail.com             | Gobi0501             |
      | kimberlydawn3+judygriger@gmail.com               | Gobi0501             |
      | kimberlydawn3+gingergriger@gmail.com             | Gobi0501             |
      | kimberlydawn3+abbygriger@gmail.com               | Gobi0501             |
      | kimberlydawn3+briangriger@gmail.com              | Gobi0501             |
      | kimberlydawn3+marleywhite@gmail.com              | Gobi0501             |
      | kimberlydawn3+muppetallen@gmail.com              | Gobi0501             |
      | kimberlydawn3+belallen@gmail.com                 | Gobi0501             |
      | kimberlydawn3+bobbyron@gmail.com                 | Gobi0501             |
      | kimberlydawn3+cindycavelli@gmail.com             | Gobi0501             |
      | kimberlydawn3+dannydebrowski@gmail.com           | Gobi0501             |
      | kimberlydawn3+sadieborder@gmail.com              | Gobi0501             |
      | kimberlydawn3+clovercat@gmail.com                | Gobi0501             |
      | kimberlydawn3+timbergriger@gmail.com             | Gobi0501             |
      | kimberlydawn3+chippygriger@gmail.om              | Gobi0501             |
      | kimberlydawn3+leomessi@gmail.com                 | Gobi0501             |
      | kimberlydawn3+twiddledee@gmail.com               | Gobi0501             |
      | kimberlydawn3+twiddledum@gmail.com               | Gobi0501             |
      | kimberlydawn3+amberzola@gmail.com                | Gobi0501             |
      | kimberlydawn3+AdamNicely@gmail.com               | Gobi0501             |
      | kimberlydawn3+elenitaggert@gmail.com             | Gobi0501             |
      | kimberlydawn3+antonellaroccuzzo@gmail.com        | Gobi0501             |
      | kimberlydawn3+lolaprice@gmail.com                | Gobi0501             |
      | kimberlydawn3+clintappleton@gmail.com            | Gobi0501             |
      | kimberlydawn3+bcr+sadie@gmail.com                | Gobi0501             |
      | kimberlydawn3+karibritz@gmail.com                | Gobi0501             |
      | kimberlydawn3+danielbritz@gmail.com              | Gobi0501             |
      | kimberlydawn3+karenprost@gmail.com               | Gobi0501             |
      | kimberlydawn3+kathypool@gmail.com                | Gobi0501             |
      | kimberlydawn3+carolinebennett@gmail.com          | Gobi0501             |
      | kimberlydawn3+kaylacline@gmail.com               | Gobi0501             |
      | kimberlydawn3+dianaburns@gmail.com               | Gobi0501             |
      | kimberlydawn3+junedoty@gmail.com                 | Gobi0501             |
      | kimberlydawn3+waynemorris@gmail.com              | Gobi0501             |
      | kimberlydawn3+iriscostello@gmail.com             | Gobi0501             |
      | kimberlydawn3+jaredrice@gmail.com                | Gobi0501             |
      | kimberlydawn3+bcr+sunnyborder@gmail.com          | Gobi0501             |
      | kimberlydawn3+gailvalez@gmail.com                | Gobi0501             |
      | kimberlydawn3+pathouse@gmail.com                 | Gobi0501             |
      | kimberlydawn3+josieburke@gmail.com               | Gobi0501             |
      | kimberlydawn3+anneellis@gmail.com                | Gobi0501             |
      | kimberlydawn3+minniebooker@gmail.com             | Gobi0501             |
      | kimberlydawn3+lauriemorton@gmail.com             | Gobi0501             |
      | kimberlydawn3+oladurham@gmail.com                | Gobi0501             |
      | kimberlydawn3+alvaflowers@gmail.com              | Gobi0501             |
      | kimberlydawn3+lanenelson@gmail.com               | Gobi0501             |
      | kimberlydawn3+raulbeck@gmail.com                 | Gobi0501             |
      | kimberlydawn3+leighkemp@gmail.com                | Gobi0501             |
      | kimberlydawn3+tylerchen@gmail.com                | Gobi0501             |
      | kimberlydawn3+kirkcrowley@gmail.com              | Gobi0501             |
      | kimberlydawn3+ethelmejia@gmail.com               | Gobi0501             |
      | kimberlydawn3+jackhuber@gmail.com                | Gobi0501             |
      | kimberlydawn3+aprilwinter@gmail.com              | Gobi0501             |
      | kimberlydawn3+autumnwinter@gmail.com             | Gobi0501             |
      | kimberlydawn3+tomashurst@gmail.com               | Gobi0501             |
      | kimberlydawn3+kerrywiley@gmail.com               | Gobi0501             |
      | kimberlydawn3+henryfranklin@gmail.com            | Gobi0501             |
      | kimberlydawn3+missyfranklin@gmail.com            | Gobi0501             |
      | kimberlydawn3+miasawyer@gmail.com                | Gobi0501             |
      | kimberlydawn3+rustyloggins@gmail.com             | Gobi0501             |
      | kimberlydawn3+williamstafford@gmail.com          | Gobi0501             |
      | kimberlydawn3+janicestafford@gmail.com           | Gobi0501             |
      | kimberlydawn3+craigvalentine@gmail.com           | Gobi0501             |
      | kimberlydawn3+adamwoods@gmail.com                | Gobi0501             |
      | kimberlydawn3+timsoto@gmail.com                  | Gobi0501             |
      | kimberlydawn3+aylarusso@gmail.com                | Gobi0501             |
      | kimberlydawn3+joshcannon@gmail.com               | Gobi0501             |
      | kimberlydawn3+lukegoff@gmail.com                 | Gobi0501             |
      | kimberlydawn3+raulott@gmail.com                  | Gobi0501             |
      | kimberlydawn3+jenmoyer@gmail.com                 | Gobi0501             |
      | kimberlydawn3+kathysosa@gmail.com                | Gobi0501             |
      | kimberlydawn3+juliankern@gmail.com               | Gobi0501             |
      | kimberlydawn3+elmomata@gmail.com                 | Gobi0501             |
      | kimberlydawn3+sarahmarquez@gmail.com             | Gobi0501             |
      | kimberlydawn3+sheilarivas@gmail.com              | Gobi0501             |
      | kimberlydawn3+brendansalazar@gmail.com           | Gobi0501             |
      | kimberlydawn3+julianaburke@gmail.com             | Gobi0501             |
      | kimberlydawn3+percyyu@gmail.com                  | Gobi0501             |
      | kimberlydawn3+aishaway@gmail.com                 | Gobi0501             |
