Feature: Validation users

  @validation_users_register_group_2
  Scenario Outline: Validation users in register group 2
    * that login with the 'https://possum-kingdom-open-water-swim-4lzlpd.public-staging.colliegives.com/experience/cm1gu0wdu039n0alb8jel9br0'
    Given that the user open page
      | userRegistration   | passwordRegistration   |
      | <userRegistration> | <passwordRegistration> |

    Examples:
      | userRegistration                        | passwordRegistration |
      | kimberlydawn3+joaquinklein@gmail.com    | Gobi0501             |
      | kimberlydawn3+lonfisher@gmail.com       | Gobi0501             |
      | kimberlydawn3+vernonbonilla@gmail.com   | Gobi0501             |
      | kimberlydawn3+conradmorse@gmail.com     | Gobi0501             |
      | kimberlydawn3+darrelgibson@gmail.com    | Gobi0501             |
      | kimberlydawn3+conniehanna@gmail.com     | Gobi0501             |
      | kimberlydawn3+phoebewiley@gmail.com     | Gobi0501             |
      | kimberlydawn3+kelseyboyle@gmail.com     | Gobi0501             |
      | kimberlydawn3+rosariokidd@gmail.com     | Gobi0501             |
      | kimberlydawn3+brianshaw@gmail.com       | Gobi0501             |
      | kimberlydawn3+cloverthecat@gmail.com    | Gobi0501             |
      | kimberlydawn3+abelriley@gmail.com       | Gobi0501             |
      | kimberlydawn3+sonyaeverett@gmail.com    | Gobi0501             |
      | kimberlydawn3+alexispatton@gmail.com    | Gobi0501             |
      | kimberlydawn3+janetrider@gmail.com      | Gobi0501             |
      | kimberlydawn3+billkline@gmail.com       | Gobi0501             |
      | kimberlydawn3+reneefuller@gmail.com     | Gobi0501             |
      | kimberlydawn3+iristate@gmail.com        | Gobi0501             |
      | kimberlydawn3+bethhaas@gmail.com        | Gobi0501             |
      | kimberlydawn3+gailroe@gmail.com         | Gobi0501             |
      | kimberlydawn3+parquearvi@gmail.com      | Gobi0501             |
      | kimberlydawn3+nellbowen@gmail.com       | Gobi0501             |
      | kimberlydawn3+rogercross@gmail.com      | Gobi0501             |
      | kimberlydawn3+carsonmains@gmail.com     | Gobi0501             |
      | kimberlydawn3+evelynblair@gmail.com     | Gobi0501             |
      | kimberlydawn3+tarapage@gmail.com        | Gobi0501             |
      | kimberlydawn3+charlesbrown@gmail.com    | Gobi0501             |
      | kimberlydawn3+bcr+bleu@gmail.com        | Gobi0501             |
      | kimberlydawn3+corineallen@gmail.com     | Gobi0501             |
      | kimberlydawn3+sandywhite@gmail.com      | Gobi0501             |
      | kimberlydawn3+nancylake@gmail.com       | Gobi0501             |
      | kimberlydawn3+jilliandoyle@gmail.com    | Gobi0501             |
      | kimberlydawn3+keithsmall@gmail.com      | Gobi0501             |
      | kimberlydawn3+cecilswift@gmail.com      | Gobi0501             |
      | kimberlydawn3+lizzybrant@gmail.com      | Gobi0501             |
      | kimberlydawn3+andrecoyle@gmail.com      | Gobi0501             |
      | kimberlydawn3+bcr+clover@gmail.com      | Gobi0501             |
      | kimberlydawn3+marklamb@gmail.com        | Gobi0501             |
      | kimberlydawn3+betsyhowe@gmail.com       | Gobi0501             |
      | kimberlydawn3+benwatchik@gmail.com      | Gobi0501             |
      | kimberlydawn3+laurawatchik@gmail.com    | Gobi0501             |
      | KIMBERLYDAWN3+CHadwatchik@gmail.com     | Gobi0501             |
      | KIMBERLYDAWN3+johnfuller@gmail.com      | Gobi0501             |
      | kimberlydawn3+maryfuller@gmail.com      | Gobi0501             |
      | kimberlydawn3+larryfuller@gmail.com     | Gobi0501             |
      | kimberlydawn3+charlottefuller@gmail.com | Gobi0501             |
      | kimberlydawn3+tommynicely@gmail.com     | Gobi0501             |
      | kimberlydawn3+jacknicely@gmail.com      | Gobi0501             |
      | kimberlydawn3+jasminparis@gmail.com     | Gobi0501             |
      | kimberlydawn3+annakirk@gmail.com        | Gobi0501             |
      | kimberlydawn3+matildawalter@gmail.com   | Gobi0501             |
      | kimberlydawn3+patrickbarlow@gmail.com   | Gobi0501             |
      | kimberlydawn3+corymacdonald@gmail.com   | Gobi0501             |
      | kimberlydawn3+liliansandoval@gmail.com  | Gobi0501             |
      | kimberlydawn3+heidiharper@gmail.com     | Gobi0501             |
      | kimberlydawn3+jasperwalsh@gmail.com     | Gobi0501             |
      | kimberlydawn3+ellisolsen@gmail.com      | Gobi0501             |
      | kimberlydawn3+sallywarren@gmail.com     | Gobi0501             |
      | kimberlydawn3+markknight@gmail.com      | Gobi0501             |
      | kimberlydawn3+kierathomas@gmail.com     | Gobi0501             |
      | kimberlydawn3+steffanmaddox@gmail.com   | Gobi0501             |
      | kimberlydawn3+johnvega@gmail.com        | Gobi0501             |
      | kimberlydawn3+lanceoliver@gmail.com     | Gobi0501             |
      | kimberlydawn3+jameswalton@gmail.com     | Gobi0501             |
      | kimberlydawn3+chrislotta@gmail.com      | Gobi0501             |
      | kimberlydawn3+rogerplanck@gmail.com     | Gobi0501             |
      | kimberlydawn3+stevesimon@gmail.com      | Gobi0501             |
      | kimberlydawn3+pamness@gmail.com         | Gobi0501             |
      | kimberlydawn3+joshwalvern@gmail.com     | Gobi0501             |
      | kimberlydawn3+rhystaylor@gmail.com      | Gobi0501             |
      | Kimberlydawn3+jaimemalenky@gmail.com    | Gobi0501             |
      | Kimberlydawn3+paulrevere@gmail.com      | Gobi0501             |
      | Kimberlydawn3+jamesmadison@gmail.com    | Gobi0501             |
      | kimberlydawn3+ms+main@gmail.com         | Gobi0501             |
      | kimberlydawn3+marshallmain@gmail.com    | Gobi0501             |
      | kimberlydawn3+daisymae@gmail.com        | Gobi0501             |
      | kimberlydawn3+elizabethharmon@gmail.com | Gobi0501             |
      | kimberlydawn3+daisymae2@gmail.com       | Gobi0501             |
      | kimberlydawn3+laurelmae@gmail.com       | Gobi0501             |
      | kimberlydawn3+lisayoung@gmail.com       | Gobi0501             |
      | kimberlydawn3+larkinleigh@gmail.com     | Gobi0501             |
      | kimberlydawn3+carolbell@gmail.com       | Gobi0501             |
      | kimberlydawn3+laythemontaine@gmail.com  | Gobi0501             |
      | kimberlydawn3+peterholt@gmail.com       | Gobi0501             |
      | kimberlydawn3+lynnettelee@gmail.com     | Gobi0501             |
      | kimberlydawn3+erinmaynard@gmail.com     | Gobi0501             |
      | kimberlydawn3+micahcrawford@gmail.com   | Gobi0501             |
      | kimberlydawn3+saraconley@gmail.com      | Gobi0501             |
      | kimberlydawn3+leaschmidt@gmail.com      | Gobi0501             |
      | kimberlydawn3+jamisonfrench@gmail.com   | Gobi0501             |
      | kimberlydawn3+devonbarnes@gmail.com     | Gobi0501             |
      | kimberlydawn3+kirstenmcgee@gmail.com    | Gobi0501             |
      | kimberlydawn3+tyreewilson@gmail.com     | Gobi0501             |
      | kimberlydawn3+bobbicollier@gmail.com    | Gobi0501             |
      | kimberlydawn3+arielliu@gmail.com        | Gobi0501             |
      | kimberlydawn3+kurtkaiser@gmail.com      | Gobi0501             |
      | kimberlydawn3+lilliehood@gmail.com      | Gobi0501             |
      | kimberlydawn3+quinnhensley@gmail.com    | Gobi0501             |
      | kimberlydawn3+tylermcmillan@gmail.com   | Gobi0501             |
      | kimberlydawn3+dougjordan@gmail.com      | Gobi0501             |
      | kimberlydawn3+sethkey@gmail.com         | Gobi0501             |
      | kimberlydawn3+elisaballard@gmail.com    | Gobi0501             |
      | kimberlydawn3+emmawagner@gmail.com      | Gobi0501             |
      | kimberlydawn3+stephaniajoy@gmail.com    | Gobi0501             |
      | kimberlydawn3+dianemallum@gmail.com     | Gobi0501             |
      | kimberlydawn3+lanemallum@gmail.com      | Gobi0501             |
      | kimberlydawn3+jessicanevar@gmail.com    | Gobi0501             |
      | kimberlydawn3+bethanykline@gmail.com    | Gobi0501             |
      | kimberlydawn3+rachelsmith@gmail.com     | Gobi0501             |
      | kimberlydawn3+karipratt@gmail.com       | Gobi0501             |
      | kimberlydawn3+klk@gmail.com             | Gobi0501             |
      | kimberlydawn3+oak+emerson@gmail.com     | Gobi0501             |
      | kimberlydawn3+weldoncook@gmail.com      | Gobi0501             |
      | kimberlydawn3+kaylabraker@gmail.com     | Gobi0501             |
      | kimberlydawn3+jensonlayton@gmail.com    | Gobi0501             |
      | kimberlydawn3+melissalayton@gmail.com   | Gobi0501             |
      | kimberlydawn3+timothylayton@gmail.com   | Gobi0501             |
      | kimberlydawn3+carolinelayton@gmail.com  | Gobi0501             |
      | kimberlydawn3+jacksonnottin@gmail.com   | Gobi0501             |
      | kimberlydawn3+clairetrall@gmail.com     | Gobi0501             |
      | kimberlydawn3+paulpearson@gmail.com     | Gobi0501             |
      | kimberlydawn3+meganbarns@gmail.com      | Gobi0501             |
      | kimberlydawn3+evanellis@gmail.com       | Gobi0501             |
      | kimberlydawn3+ethanhobbs@gmail.com      | Gobi0501             |
      | kimberlydawn3+calvinwatterson@gmail.com | Gobi0501             |
      | kimberlydawn3+violetshipman@gmail.com   | Gobi0501             |
      | kimberlydawn3+charlieschnapp@gmail.com  | Gobi0501             |
      | kimberlydawn3+linusgarfin@gmail.com     | Gobi0501             |
      | kimberlydawn3+OAK+weldoncook@gmail.com  | Gobi0501             |
      | kimberlydawn3+JGC+Judy@gmail.com        | Gobi0501             |
      | kimberlydawn3+ncc+natalie@gmail.com     | Gobi0501             |
      | kimberlydawn3+troybridges@gmail.com     | Gobi0501             |
      | kimberlydawn3+marianfisher@gmail.com    | Gobi0501             |
      | kimberlydawn3+caitlinspence@gmail.com   | Gobi0501             |
      | kimberlydawn3+aliciagrimes@gmail.com    | Gobi0501             |
      | kimberlydawn3+emmaogden@gmail.com       | Gobi0501             |
      | kimberlydawn3+lizgibson@gmail.com       | Gobi0501             |
      | kimberlydawn3+tomjones@gmail.com        | Gobi0501             |
      | kimberlydawn3+hilarymaynor@gmail.com    | Gobi0501             |
      | Kimberlydawn3+sadielane@gmail.com       | Gobi0501             |
      | kimberlydawn3+jtw+john@gmail.com        | Gobi0501             |
      | kimberlydawn3+emilybarringer@gmail.com  | Gobi0501             |
      | kimberlydawn3+wadetalbot@gmail.com      | Gobi0501             |
      | kimberlydawn3+lindayoung@gmail.com      | Gobi0501             |
      | kimberlydawn3+noahwylie@gmail.com       | Gobi0501             |
      | kimberlydawn3+gabbymoore@gmail.com      | Gobi0501             |
      | kimberlydawn3+amandatrainer@gmail.com   | Gobi0501             |
      | kimberlydawn3+stephanieplatt@gmail.com  | Gobi0501             |
      | kimberlydawn3+meganenster@gmail.com     | Gobi0501             |
      | kimberlydawn3+hannahflint@gmail.com     | Gobi0501             |
      | kimberlydawn3+kellywaint@gmail.com      | Gobi0501             |
      | kimberlydawn3+pollyragner@gmail.com     | Gobi0501             |
      | kimberlydawn3+debbyonstrain@gmail.com   | Gobi0501             |
      | kimberlydawn3+rebeccaamos@gmail.com     | Gobi0501             |
      | kimberlydawn3+kristenbrowning@gmail.com | Gobi0501             |
      | kimberlydawn3+allimadden@gmail.com      | Gobi0501             |
      | kimberlydawn3+sloanewaverly@gmail.com   | Gobi0501             |
      | kimberlydawn3+dianenewton@gmail.com     | Gobi0501             |
      | kimberlydawn3+JGC+Brian@gmail.com       | Gobi0501             |
      | kimberlydawn3+carolinenelson@gmail.com  | Gobi0501             |
      | kimberlydawn3+pop+pluto@gmail.com       | Gobi0501             |
      | kimberlydawn3+pop+jupiter@gmail.com     | Gobi0501             |
      | kimberlydawn3+redkitsune@gmail.com      | Gobi0501             |
      | kimberlydawn3+annabelprice@gmail.com    | Gobi0501             |
      | kimberlydawn3+matthewsalinas@gmail.com  | Gobi0501             |
      | kimberlydawn3+oak+wilder@gmail.com      | Gobi0501             |
      | kimberlydawn3+wyattlyons@gmail.com      | Gobi0501             |
      | kimberlydawn3+jtw+lizzie@gmail.com      | Gobi0501             |
      | kimberlydawn3+fca@gmail.com             | Gobi0501             |
      | kimberlydawn3+fca+kim@gmail.com         | Gobi0501             |
      | kimberlydawn3+oliviadavos@gmail.com     | Gobi0501             |
      | kimberlydawn3+sambowen@gmail.com        | Gobi0501             |
      | kimberlydawn3+awr+fireball@gmail.com    | Gobi0501             |
      | kimberlydawn3+mollycrowly@gmail.com     | Gobi0501             |
      | kimberlydawn3+lucawaverly@gmail.com     | Gobi0501             |
      | kimberlydawn3+samholden@gmail.com       | Gobi0501             |
      | kimberlydawn3+bennettchall@gmail.com    | Gobi0501             |
      | Kimberlydawn3+janetkitsane@gmail.com    | Gobi0501             |
      | kimberlydawn3+garrettford@gmail.com     | Gobi0501             |
      | kimberlydawn3+willrocha@gmail.com       | Gobi0501             |
      | kimberlydawn3+hudsonblue@gmail.com      | Gobi0501             |
      | kimberlydawn3+xanderkaid@gmail.com      | Gobi0501             |
      | kimberlydawn3+rebeccabrown@gmail.com    | Gobi0501             |
      | kimberlydawn3+larkinleigh6@gmail.com    | Gobi0501             |
      | kimberlydawn3+helenwright@gmail.com     | Gobi0501             |
      | Kimberlydawn3+haroldkeep@gmail.com      | Gobi0501             |
      | kimberlydawn3+mabelnellis@gmail.com     | Gobi0501             |
      | Kimberlydawn3+bennettcake@gmail.com     | Gobi0501             |
      | kim.collie24@gmail.com                  | Gobi0501             |
      | kimdawn0614@gmail.com                   | Gobi0501             |
