name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Permite la ejecución manual

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests with Runner 1
        run: ./gradlew clean test --tests com.reto.runners.ParallelRunner -Dcucumber.filter.tags="@regression_register_pipeline" aggregate -i

  job2:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests with Runner 2
        run: ./gradlew clean test --tests com.reto.runners.ParallelRunner -Dcucumber.filter.tags="@regression_donation_pipeline" aggregate -i
