name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Permite la ejecución manual

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'

      - name: Run tests with Runner 1
        run: ./gradlew clean test --tests com.reto.runners.ParallelRunner -Dcucumber.filter.tags="@regression_register_pipeline" aggregate -i

  job2:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'

      - name: Run tests with Runner 2
        run: ./gradlew clean test --tests com.reto.runners.ParallelRunner -Dcucumber.filter.tags="@regression_donation_pipeline" aggregate -i
